import 'package:rukunin/modules/marketplace/models/product.dart';

List<Product> cartItems = [
  Product(
    name: 'Kopi Arabica Gayo 250g',
    seller: 'Gayo Brew',
    price: 85000,
    badge: 'Best Seller',
    description: 'Kopi Arabica premium dari dataran tinggi Gayo.',
    isDiscount: true,
    rating: 4.8,
    quantity: 1,
  ),
  Product(
    name: 'Teh Hijau Organik 100g',
    seller: 'GreenLeaf',
    price: 45000,
    badge: 'Organic',
    description: 'Teh hijau organik dengan aroma segar dan menenangkan.',
    rating: 4.5,
    quantity: 2,
  ),
  Product(
    name: 'Madu Hutan Asli 500ml',
    seller: 'Nusantara Honey',
    price: 120000,
    badge: 'Natural',
    description: 'Madu hutan murni tanpa campuran.',
    isDiscount: false,
    rating: 4.7,
    quantity: 1,
  ),
  Product(
    name: 'Minyak Zaitun Extra Virgin 250ml',
    seller: 'OliveHouse',
    price: 70000,
    badge: 'Healthy Choice',
    description: 'Minyak zaitun extra virgin untuk masakan sehat.',
    rating: 4.6,
    quantity: 1,
  ),
  Product(
    name: 'Beras Merah Organik 1kg',
    seller: 'HealthyFarm',
    price: 55000,
    badge: 'Organic',
    description: 'Beras merah organik kaya serat dan nutrisi.',
    rating: 4.4,
    quantity: 3,
  ),
  Product(
    name: 'Coklat Dark 80%',
    seller: 'Cocoa Bliss',
    price: 38000,
    badge: 'Premium',
    description: 'Coklat hitam 80% dengan rasa pahit manis seimbang.',
    isDiscount: true,
    rating: 4.9,
    quantity: 1,
  ),
  Product(
    name: 'Granola Mix 500g',
    seller: 'FitSnack',
    price: 68000,
    badge: 'Healthy Snack',
    description: 'Granola campuran oats, kacang, dan madu.',
    rating: 4.3,
    quantity: 2,
  ),
  Product(
    name: 'Susu Almond 1L',
    seller: 'Almondy',
    price: 45000,
    badge: 'Dairy Free',
    description: 'Susu almond tanpa pemanis tambahan.',
    isDiscount: false,
    rating: 4.2,
    quantity: 1,
  ),
  Product(
    name: 'Minyak Kelapa Murni 500ml',
    seller: 'CocoPure',
    price: 65000,
    badge: 'Natural',
    description: 'Minyak kelapa murni serbaguna.',
    rating: 4.5,
    quantity: 1,
  ),
  Product(
    name: 'Selai Kacang Crunchy 350g',
    seller: 'NuttyJar',
    price: 52000,
    badge: 'Crunchy',
    description: 'Selai kacang dengan tekstur crunchy yang lezat.',
    rating: 4.6,
    quantity: 2,
  ),
];

