import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:rukunin/theme/app_colors.dart';
import 'package:rukunin/widgets/input_decorations.dart';
import 'package:rukunin/repositories/kwitansi_repository.dart';

class KwitansiTemplatePage extends StatefulWidget {
  const KwitansiTemplatePage({super.key});

  @override
  State<KwitansiTemplatePage> createState() => _KwitansiTemplatePageState();
}

class _KwitansiTemplatePageState extends State<KwitansiTemplatePage> {
  final _formKey = GlobalKey<FormState>();
  final _titleCtrl = TextEditingController();
  // number format and RT/RW are generated by system; no manual input here
  final _treasurerCtrl = TextEditingController();
  final _footerCtrl = TextEditingController(
    text: 'Simpan kwitansi ini sebagai bukti pembayaran yang sah',
  );

  String? _logoPath;
  String? _signaturePath;
  final ImagePicker _picker = ImagePicker();
  bool _saving = false;

  @override
  void dispose() {
    _titleCtrl.dispose();
    _treasurerCtrl.dispose();
    _footerCtrl.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    // Prefill treasurer name to make it easy to edit
    _treasurerCtrl.text = 'Bendahara';
  }

  Future<void> _pickLogo() async {
    try {
      final XFile? f = await _picker.pickImage(
        source: ImageSource.gallery,
        maxWidth: 1200,
      );
      if (f == null) return;
      final ok = await _validateImageFile(f);
      if (!ok) return;
      final saved = await _savePickedFile(f);
      if (saved == null) return;
      setState(() => _logoPath = saved);
    } catch (e) {
      debugPrint('Error picking logo: $e');
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Gagal memilih logo: $e'),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }

  Future<void> _pickSignature() async {
    try {
      final XFile? f = await _picker.pickImage(
        source: ImageSource.gallery,
        maxWidth: 1200,
      );
      if (f == null) return;
      final ok = await _validateImageFile(f);
      if (!ok) return;
      final saved = await _savePickedFile(f);
      if (saved == null) return;
      setState(() => _signaturePath = saved);
    } catch (e) {
      debugPrint('Error picking signature: $e');
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Gagal memilih tanda tangan: $e'),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }

  Future<bool> _validateImageFile(XFile file) async {
    final name = file.name.toLowerCase();
    final allowed = ['jpg', 'jpeg', 'png'];
    final parts = name.split('.');
    final ext = parts.length > 1 ? parts.last : '';
    if (!allowed.contains(ext)) {
      if (!mounted) return false;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Format file tidak didukung (JPG/PNG)'),
          backgroundColor: AppColors.error,
        ),
      );
      return false;
    }
    try {
      final len = await file.length();
      if (len > 5 * 1024 * 1024) {
        if (!mounted) return false;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Ukuran file maksimal 5MB'),
            backgroundColor: AppColors.error,
          ),
        );
        return false;
      }
    } catch (_) {
      // if we can't read length, allow and hope for the best
    }
    return true;
  }

  Future<void> _saveTemplate() async {
    if (!(_formKey.currentState?.validate() ?? false)) return;
    setState(() => _saving = true);
    final tpl = KwitansiTemplate(
      id: 'template_default',
      logoPath: _logoPath,
      title: _titleCtrl.text.trim(),
      numberFormat: '', // system will generate number when used
      rw: '',
      rt: '',
      treasurerName: _treasurerCtrl.text.trim(),
      signaturePath: _signaturePath,
      footerNote: _footerCtrl.text.trim(),
    );
    await KwitansiRepository().saveTemplate(tpl);
    if (!mounted) return;
    setState(() => _saving = false);
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text('Template kwitansi tersimpan'),
        backgroundColor: AppColors.primary,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
    );
  }

  Future<String?> _savePickedFile(XFile file) async {
    try {
      final appDir = await getApplicationDocumentsDirectory();
      final targetDir = Directory(p.join(appDir.path, 'kwitansi_templates'));
      if (!await targetDir.exists()) await targetDir.create(recursive: true);
      final filename =
          '${DateTime.now().millisecondsSinceEpoch}_${p.basename(file.path)}';
      final newPath = p.join(targetDir.path, filename);
      // Use XFile.saveTo if available, otherwise fallback to copy
      try {
        await file.saveTo(newPath);
      } catch (_) {
        await File(file.path).copy(newPath);
      }
      return newPath;
    } catch (e) {
      debugPrint('Failed to persist picked file: $e');
      if (!mounted) return null;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Gagal menyimpan file: $e'),
          backgroundColor: AppColors.error,
        ),
      );
      return null;
    }
  }

  Widget _uploadBox({
    required String label,
    required VoidCallback onTap,
    String? previewPath,
  }) {
    return MouseRegion(
      cursor: SystemMouseCursors.click,
      child: GestureDetector(
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: AppColors.primary.withOpacity(0.3),
              width: 2,
              style: BorderStyle.solid,
            ),
          ),
          child: Column(
            children: [
              if (previewPath == null) ...[
                const Icon(
                  Icons.cloud_upload_outlined,
                  size: 40,
                  color: AppColors.primary,
                ),
                const SizedBox(height: 8),
                Text(
                  label,
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: Colors.grey[700],
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Format: JPG, PNG (Max 5MB)',
                  style: TextStyle(fontSize: 12, color: Colors.grey[500]),
                ),
              ] else ...[
                ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: Image.file(
                    File(previewPath),
                    height: 80,
                    fit: BoxFit.contain,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'Tap untuk mengganti file',
                  style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                ),
              ],
              if (kIsWeb) ...[
                const SizedBox(height: 6),
                const Text(
                  'Klik untuk memilih file',
                  style: TextStyle(
                    fontSize: 11,
                    color: AppColors.primary,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        foregroundColor: Colors.black,
        title: const Text(
          'Buat Template Kwitansi',
          style: TextStyle(fontWeight: FontWeight.w700),
        ),
      ),
      backgroundColor: Colors.grey[50],
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 900),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Info card describing this page
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        colors: [
                          AppColors.primary.withOpacity(0.15),
                          AppColors.primary.withOpacity(0.05),
                        ],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(
                        color: AppColors.primary.withOpacity(0.15),
                      ),
                    ),
                    child: Row(
                      children: [
                        Container(
                          width: 56,
                          height: 56,
                          decoration: BoxDecoration(
                            color: AppColors.primary,
                            borderRadius: BorderRadius.circular(14),
                          ),
                          child: const Icon(
                            Icons.receipt_long,
                            color: Colors.white,
                            size: 28,
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text(
                                'Template Kwitansi',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w700,
                                  color: Colors.black,
                                ),
                              ),
                              const SizedBox(height: 4),
                              Text(
                                'Buat template kwitansi untuk iuran warga. Sistem akan mengisi data keluarga dan nomor kwitansi secara otomatis saat digunakan.',
                                style: TextStyle(
                                  fontSize: 13,
                                  color: Colors.grey[700],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 12),
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.04),
                          blurRadius: 8,
                          offset: const Offset(0, 2),
                        ),
                      ],
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        const Text(
                          'Pengaturan Template',
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        const SizedBox(height: 12),
                        LayoutBuilder(
                          builder: (context, constraints) {
                            final logoWidget = Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                const Text(
                                  'Logo / Header',
                                  style: TextStyle(
                                    fontSize: 12,
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                                const SizedBox(height: 8),
                                _uploadBox(
                                  previewPath: _logoPath,
                                  label: 'Unggah Logo',
                                  onTap: _pickLogo,
                                ),
                              ],
                            );

                            final signWidget = Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                const Text(
                                  'Tanda Tangan',
                                  style: TextStyle(
                                    fontSize: 12,
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                                const SizedBox(height: 8),
                                _uploadBox(
                                  previewPath: _signaturePath,
                                  label: 'Unggah Tanda Tangan',
                                  onTap: _pickSignature,
                                ),
                              ],
                            );

                            // Always stack upload widgets vertically and use full width,
                            // so uploads are not cramped into a single row.
                            return Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                logoWidget,
                                const SizedBox(height: 12),
                                signWidget,
                              ],
                            );
                          },
                        ),
                        const SizedBox(height: 12),
                        TextFormField(
                          controller: _titleCtrl,
                          decoration: buildInputDecoration('Judul Kwitansi'),
                          validator: (v) => (v == null || v.isEmpty)
                              ? 'Judul tidak boleh kosong'
                              : null,
                        ),
                        const SizedBox(height: 12),
                        TextFormField(
                          controller: _treasurerCtrl,
                          decoration: buildInputDecoration('Nama Bendahara'),
                        ),
                        const SizedBox(height: 12),
                        TextFormField(
                          controller: _footerCtrl,
                          decoration: buildInputDecoration('Catatan Kaki'),
                          minLines: 2,
                          maxLines: 4,
                        ),
                        const SizedBox(height: 16),
                        Row(
                          children: [
                            Expanded(
                              child: OutlinedButton(
                                onPressed: () async {
                                  // preview
                                  final tpl = KwitansiTemplate(
                                    id: 'preview',
                                    logoPath: _logoPath,
                                    title: _titleCtrl.text.trim(),
                                    numberFormat:
                                        '', // generated by system on actual use
                                    rw: '',
                                    rt: '',
                                    treasurerName: _treasurerCtrl.text.trim(),
                                    signaturePath: _signaturePath,
                                    footerNote: _footerCtrl.text.trim(),
                                  );
                                  // show a simple preview dialog
                                  showDialog(
                                    context: context,
                                    builder: (ctx) {
                                      return AlertDialog(
                                        title: const Text('Preview Kwitansi'),
                                        content: SizedBox(
                                          width: 400,
                                          child: _buildPreview(tpl),
                                        ),
                                        actions: [
                                          TextButton(
                                            onPressed: () =>
                                                Navigator.of(ctx).pop(),
                                            child: const Text('Tutup'),
                                          ),
                                        ],
                                      );
                                    },
                                  );
                                },
                                child: const Text('Preview'),
                              ),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: ElevatedButton(
                                onPressed: _saving ? null : _saveTemplate,
                                child: _saving
                                    ? const SizedBox(
                                        height: 16,
                                        width: 16,
                                        child: CircularProgressIndicator(
                                          strokeWidth: 2,
                                          color: Colors.white,
                                        ),
                                      )
                                    : const Text('Simpan Template'),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildPreview(KwitansiTemplate tpl) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: AppColors.border),
        color: Colors.white,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          if (tpl.logoPath != null)
            Center(child: Image.file(File(tpl.logoPath!), height: 60)),
          const SizedBox(height: 8),
          Text(
            tpl.title,
            textAlign: TextAlign.center,
            style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 8),
          Text(
            tpl.numberFormat.isEmpty
                ? 'No: (otomatis)'
                : 'No: ${tpl.numberFormat}',
            style: TextStyle(color: Colors.grey[700]),
          ),
          const Divider(),
          const SizedBox(height: 8),
          _rowLabelValue('Kepala Keluarga', 'Nama Keluarga'),
          _rowLabelValue(
            'Alamat',
            'Alamat Warga RT 0${tpl.rt} / RW 0${tpl.rw}',
          ),
          _rowLabelValue('Jenis Iuran', 'Iuran Bulanan'),
          _rowLabelValue('Jumlah', 'Rp 0'),
          _rowLabelValue('Tanggal', '01 Jan 2025'),
          const SizedBox(height: 12),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Text(tpl.treasurerName, textAlign: TextAlign.center),
              ),
              if (tpl.signaturePath != null)
                Expanded(
                  child: Image.file(File(tpl.signaturePath!), height: 48),
                ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            tpl.footerNote,
            style: TextStyle(color: Colors.grey[700], fontSize: 12),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }

  Widget _rowLabelValue(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        children: [
          Expanded(
            flex: 3,
            child: Text(
              label,
              style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13),
            ),
          ),
          const SizedBox(width: 8),
          Expanded(flex: 5, child: Text(value)),
        ],
      ),
    );
  }
}
