// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRSUiH4hlRaWbaTobKa7vysAUfnz1gg4',
    appId: '1:1029176612701:web:fac40231355d882f1fbab4',
    messagingSenderId: '1029176612701',
    projectId: 'rukunin-app',
    authDomain: 'rukunin-app.firebaseapp.com',
    storageBucket: 'rukunin-app.firebasestorage.app',
    measurementId: 'G-M6PYPXE96P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsylITH2BwLK5OBnh3NystqMSX2YSDmH4',
    appId: '1:1029176612701:android:57d0d935ee0d3e171fbab4',
    messagingSenderId: '1029176612701',
    projectId: 'rukunin-app',
    storageBucket: 'rukunin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_HIjBKp-vWQwTNk5iAoTui0K9uXWNlI',
    appId: '1:1029176612701:ios:2a8a08208e8beee01fbab4',
    messagingSenderId: '1029176612701',
    projectId: 'rukunin-app',
    storageBucket: 'rukunin-app.firebasestorage.app',
    iosBundleId: 'com.squadronteam.rukunin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi_HIjBKp-vWQwTNk5iAoTui0K9uXWNlI',
    appId: '1:1029176612701:ios:2a8a08208e8beee01fbab4',
    messagingSenderId: '1029176612701',
    projectId: 'rukunin-app',
    storageBucket: 'rukunin-app.firebasestorage.app',
    iosBundleId: 'com.squadronteam.rukunin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeRSUiH4hlRaWbaTobKa7vysAUfnz1gg4',
    appId: '1:1029176612701:web:c7c336fc29bca8db1fbab4',
    messagingSenderId: '1029176612701',
    projectId: 'rukunin-app',
    authDomain: 'rukunin-app.firebaseapp.com',
    storageBucket: 'rukunin-app.firebasestorage.app',
    measurementId: 'G-Y51XTTC0HH',
  );
}
